version: '2'
services:
  locust-master:
    build: .
    ports:
      - 8089:8089
    entrypoint:
      - locust
      - -f
      - /locustfile.py
      - --master-bind-port=5557
      - --master-bind-host=locust-master
  locust-slave-1:
    build: .
    links:
      - locust-master
    entrypoint:
      - locust
      - -f
      - /locustfile.py
      - --slave
      - --master-host=locust-master
      - --master-port=5557

  locust-slave-2:
    build: .
    links:
      - locust-master
    entrypoint:
      - locust
      - -f
      - /locustfile.py
      - --slave
      - --master-host=locust-master
      - --master-port=5557
