version: '2'
services:
  target:
    image: nginx

  master:
    build: .
    ports:
      - 8089:8089
    entrypoint:
      - locust
      - -f
      - /locustfile.py
      - --master
    links:
      - target:target

  slave:
    build: .
    links:
      - master
    entrypoint:
      - locust
      - -f
      - /locustfile.py
      - --slave
      - --master-host=master
      - --master-port=5557
